### ISSUE TITLE
Symfony3 compatibility

### ISSUE THREAD

**Issue by lenybernard** [infinite-networks/InfiniteFormBundle#56]
Hello,

I'm currently migrating some projects to Symfony3 and I use your bundle which is not ready yet.
I don't know this repo as well because we use a tiny part and I would like to know before starting that first you're not currently working on it :) and if you already think about stuffs to care about ?

**Comment by merk** [comment]
We're not currently looking at migrating to Symfony3 for any projects that rely on this bundle internally, but there have already been pull requests to update things that dont work or are not compatible.

Is there anything specific you're having a problem with?

**Comment by sasy-lingo** [comment]
I'm guessing @lenybernard is having problems with the deprecated method names, like `getName`, which raises a deprecated error in Symfony 2.8 and fatal error in 3.0+.

see for example:
https://github.com/infinite-networks/InfiniteFormBundle/blob/master/Form/Type/PolyCollectionType.php#L140-L143

If you want to support all previous versions of Symfony, maybe you should create feature branches for each of them, since 2.8 introduced breaking changes.

**Comment by stof** [comment]
There is no need to create feature branch. It is not hard to support both APIs at the same time (lots of bundles are doing it, and we explicitly thought about how such compat layer would be done when doing the changes in Symfony)

**Comment by merk** [comment]
I'm happy to accept pull requests fixing specific issues as long as they maintain BC where possible, but I'm going to need issue reports for each individual issue that you're encountering if you need assistance in fixing it, as I said above - we're not using Symfony3 at this time.

**Comment by jmclean** [comment]
Compatibility added in #60
